### ISSUE TITLE
Test Cards

### ISSUE THREAD

**Issue by voveson** [thephpleague/omnipay-payflow#11]
Throughout this library, the test card number `4242424242424242` is used as an example in the comments.  It seems as though this card number is no longer a valid test card for Payflow.  Valid card numbers can be found [here](https://developer.paypal.com/docs/classic/payflow/integration-guide/#paypal-credit-card-numbers-for-testing).

I may eventually have time to update this and submit a pull request, but for now hopefully this helps someone.

**Comment by RobvH** [comment]
Work in an organization that is committed to pay flow for some time. I'm so glad this exists and is a League package nonetheless.

**Comment by RobvH** [comment]
https://github.com/thephpleague/omnipay-payflow/pull/15 added to update test CC number.

**Comment by RobvH** [comment]
@delatbabel This issue should be resolved by PR #15 

We should be able to close this as resolved.
