### ISSUE TITLE
Tag 2.3.0 stable

### ISSUE THREAD

**Issue by RobvH** [thephpleague/omnipay-payflow#20]
@delatbabel we are currently running my downstream 2.3.0 in production which has pull request #19 merged. When you can, I suggest we merge that and JT's PR and tag 2.3.0 so that I can switch back to the upstream repo.

Regards,
Rob_vH

**Comment by delatbabel** [comment]
OK can do.  I note that on PR #17 I asked you to confirm that that worked in production and get back to me to tag for release but I didn't hear back.  If you have time can you also please submit one PR to remove PHP 5.3 from .travis.yml -- I think that's the only thing now causing the tests to fail.

**Comment by delatbabel** [comment]
Tagged.

**Comment by delatbabel** [comment]
nvm, someone else already made the change to remove PHP 5.3.  Thanks anyway.

**Comment by RobvH** [comment]
Sorry, yes, we are using it in production. :)
