### ISSUE TITLE
Tag a last version for 2.x

### ISSUE THREAD

**Issue by Korri** [thephpleague/omnipay-payflow#26]
Can you please tag a version with commit https://github.com/thephpleague/omnipay-payflow/commit/88fb22e1203caff81e106abd4a9b77fc32bb1708 as the changed after this are backward incompatible?

**Comment by barryvdh** [comment]
yes done

**Comment by Korri** [comment]
Hey, I don't see any new tag, is it possible you forgot to push it?

**Comment by barryvdh** [comment]
Oh sorry, I tagged v3 indeed.

**Comment by barryvdh** [comment]
This then https://github.com/thephpleague/omnipay-payflow/releases/tag/v2.3.1

**Comment by Korri** [comment]
Thanks, that's perfect!
