### ISSUE TITLE
Currency not being passed

### ISSUE THREAD

**Issue by dvlsg** [thephpleague/omnipay-payflow#5]
We recently ran across an issue with a client in Australia using PayFlow where they were unable to pass `AUD` as a currency, and `USD` was being picked by default.

Currency was provided to the PayFlow library through the Omnipay request parameters, but I noticed the actual request being sent to PayFlow's API from the PayFlow driver did not contain a `CURRENCY` setting.

The [PayFlow docs](https://developer.paypal.com/docs/classic/payflow/integration-guide/) seem a bit spare when it comes to the parameter list, but I noticed there were quite a few examples that included `CURRENCY`. Here's an example from the linked docs:

```
TRXTYPE=A&BILLTOSTREET=123 Main St.&BILLTOZIP=95131&AMT=23.45&CURRENCY=USD&INVNUM=INV12345
&PONUM=PO9876&**CREATESECURETOKEN**=Y&**SECURETOKENID**=9a9ea8208de1413abc3d60c86cb1f4c5
```

I believe adding `$data['CURRENCY']` to `getData()` in [AuthorizeRequest.php](https://github.com/thephpleague/omnipay-payflow/blob/9d86e3478dd42cbe40ab9466a7505c4f99c70ee7/src/Message/AuthorizeRequest.php#L88) might resolve the issue?

**Comment by delatbabel** [comment]
I don't have access to a PayFlow production or test account to try this out.  If you can make it work and send a PR then I will merge it.
